Repository nextcloud/integration_miro, pull requests merged in 2023-07, with the labels that each got.

#9 Fix wrong param when calling appManager->isEnabledForUser
  lib/Controller/PageController.php
Labels: bug

#4 chore: update node engines to next LTS
  package-lock.json
  package.json
Labels: automated, dependencies, 3. to review

#10 Release 1.0.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
